# Generated by Django 5.0.7 on 2024-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_bus_student_is_on_bus_student_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
