# Generated by Django 5.0.7 on 2024-11-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_driverlocation_studentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bus'),
        ),
    ]
