# Generated by Django 5.0.7 on 2024-11-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_bus_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Chưa lên xe', max_length=50),
        ),
    ]
